apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  replicas: 1

  #minReadySeconds: 30
  selector:
    matchLabels:
     app: mongodb
  template: # template for pods
    metadata:
      labels: 
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:7.0.5-jammy
        volumeMounts:
        - name: mongo-persistent-storage
          mountPath: /data/db

      volumes:
      -  name: mongo-persistent-storage
         persistentVolumeClaim:
           claimName: mongo-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: fleetman-mongodb
spec:
  # Defines the pods going to represent this Service
  # Service becomes a network endpoint for either other services
  # or mabye external users to connect to (eg browser)
  selector:
    app: mongodb
  ports:
    - name: mongoport
      port: 27017

  type: ClusterIP
